import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.JOptionPane;
import static javax.swing.text.html.HTML.Attribute.ID;
import koneksi.koneksi;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author smkiupro1
 */
public class distributor extends javax.swing.JFrame {

     private DefaultTableModel model;
    
    /**
     * Creates new form distributor
     */
    public distributor() {
        initComponents();
        loadData();
        kosong();
        
        setEnabledfalse();
    }
    
    public void setEnabledfalse(){
        txtid.setEnabled(false);
        txtnama.setEnabled(false);
        txtalamat.setEnabled(false);
        txtkota.setEnabled(false);
        txtemail.setEnabled(false);
        txttelepon.setEnabled(false);
        btnsimpan.setEnabled(false);
        btnubah.setEnabled(false);
        btnhapus.setEnabled(false);
    }
    
    public void setEnabledtrue(){
        txtid.setEnabled(true);
        txtnama.setEnabled(true);
        txtalamat.setEnabled(true);
        txtkota.setEnabled(true);
        txtemail.setEnabled(true);
        txttelepon.setEnabled(true);
        btnsimpan.setEnabled(true);
        btnubah.setEnabled(true);
        btnhapus.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        txtkota = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Distributor");

        jLabel2.setText("Nama Distributor");

        jLabel3.setText("Alamat Distributor");

        jLabel4.setText("Kota Asal");

        jLabel5.setText("Email");

        jLabel6.setText("Telepon");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidKeyTyped(evt);
            }
        });

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane1.setViewportView(txtalamat);

        txttelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtteleponKeyTyped(evt);
            }
        });

        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbarangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelbarang);

        btntambah.setText("Add New");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        btntambah.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btntambahPropertyChange(evt);
            }
        });

        btnsimpan.setText("Save");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnubah.setText("Update");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnhapus.setText("Delete");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnbatal.setText("Cancel");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        jLabel7.setText("Maksimal 15 Digit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btntambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnsimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnubah)
                        .addGap(18, 18, 18)
                        .addComponent(btnhapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnbatal)
                        .addGap(18, 18, 18)
                        .addComponent(btnclose))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtid)
                            .addComponent(txtnama)
                            .addComponent(jScrollPane1)
                            .addComponent(txtemail)
                            .addComponent(txtkota)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addComponent(jScrollPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambah)
                    .addComponent(btnsimpan)
                    .addComponent(btnubah)
                    .addComponent(btnhapus)
                    .addComponent(btnbatal)
                    .addComponent(btnclose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadData(){
        model = new DefaultTableModel();
        model.getDataVector().removeAllElements();      
        model.fireTableDataChanged();
        
        tabelbarang.setModel(model);
        model.addColumn("ID");
        model.addColumn("Nama Distributor");
        model.addColumn("Alamat Distributor");
        model.addColumn("Kota Asal");
        model.addColumn("Email");
        model.addColumn("Telepon");
        
        try{
            String sql = "SELECT * FROM tbdistributor";
            
            Connection c = koneksi.getkoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery (sql);
            
             while (r.next()){
                model.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6)
                });  
            }
             tabelbarang.setModel(model);
            }catch(SQLException e){
                System.out.println("");
        }
    }
    
    private void kosong(){
        txtid.setText(null);
        txtnama.setText(null);
        txtalamat.setText(null);
        txtkota.setText(null);
        txtemail.setText(null);
        txttelepon.setText(null);
    }
    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        setEnabledtrue();
        btntambah.setEnabled(false);
    }//GEN-LAST:event_btntambahActionPerformed

    private void tabelbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbarangMouseClicked
        // TODO add your handling code here:
 int baris = tabelbarang.getSelectedRow();
        
        if(baris == -1){
//            tak ada baris terseleksi
            return;
        }
        
        String ID = tabelbarang.getValueAt(baris, 0).toString();
        txtid.setText(ID);
        String Nama = tabelbarang.getValueAt(baris, 1).toString();
        txtnama.setText(Nama);
        String Alamat = tabelbarang.getValueAt(baris, 2).toString();
        txtalamat.setText(Alamat);
        String Kota = tabelbarang.getValueAt(baris, 3).toString();
        txtkota.setText(Kota);
        String Email = tabelbarang.getValueAt(baris, 4).toString();
        txtemail.setText(Email);
        String Telepon = tabelbarang.getValueAt(baris, 5).toString();
        txttelepon.setText(Telepon);
    }//GEN-LAST:event_tabelbarangMouseClicked

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String ID_Distributor = txtid.getText();
        String Nama_Distributor = txtnama.getText();
        String Alamat = txtalamat.getText();
        String Kota_Asal = txtkota.getText();
        String Email = txtemail.getText();
        String Telepon = txttelepon.getText();
        
        if("".equals(ID_Distributor) || "".equals(Nama_Distributor) ||
                "".equals(Alamat) ||
                "".equals(Kota_Asal) || "".equals(Email) || "".equals(Telepon))
            {
              JOptionPane.showMessageDialog(this, "Harap Lengkapi Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
            } else {
            
            try{
                Connection c = koneksi.getkoneksi();
                String sql = "INSERT INTO tbdistributor VALUES (?, ?, ?, ?, ?,?)";
                PreparedStatement p = c.prepareStatement(sql);
                
                p.setString(1, ID_Distributor);
                p.setString(2, Nama_Distributor);
                p.setString(3, Alamat);
                p.setString(4, Kota_Asal);
                p.setString(5, Email);
                p.setString(6, Telepon);
                
                p.executeUpdate();
                p.close();
                
                JOptionPane.showMessageDialog(null,
                        "Penyimpanan Data Berhasil");
                
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this,
                        e.getMessage());
            }finally{
                loadData();
                kosong();
                setEnabledfalse();
                btntambah.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btntambahPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btntambahPropertyChange
        // TODO addint i = tabeldistributor.getSelectedRow();
       
    }//GEN-LAST:event_btntambahPropertyChange

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:  
        int i = tabelbarang.getSelectedRow();
        
        if (i == -1){
//            tidak ada baris terseleksi
            JOptionPane.showMessageDialog(this,
                    "Harap Pilih Data Terlebih Dahulu",
                    "Eror", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String ID_Distributor = (String) model.getValueAt(i,0);
        String Nama = txtnama.getText();
        String Alamat = txtalamat.getText();
        String Kota = txtkota.getText();
        String Email = txtemail.getText();
        String Telepon = txttelepon.getText();
        
        try{
            Connection c = koneksi.getkoneksi();
            
            String sql = "UPDATE tbdistributor SET Nama = ?, Alamat =  ?, KotaAsal=  ?, Email=  ?,  Telepon=  ? WHERE IDDistributor =  ?";
            
            
            PreparedStatement p = c.prepareStatement(sql);
            
            
                p.setString(1, Nama);
                p.setString(2, Alamat);
                p.setString(3, Kota);
                p.setString(4, Email);
                p.setString(5, Telepon);
                p.setString(6, ID_Distributor);
                
            p.executeUpdate();
            p.close();
            
            JOptionPane.showMessageDialog(null,
                    "Ubah Data Berhasil");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,
                    "Terjadi Eror" + e.getMessage());
        }finally{
            loadData();
            kosong();
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
      int i = tabelbarang.getSelectedRow();
        
        if (i == -1){
//            tidak ada baris terseleksi
            JOptionPane.showMessageDialog(this,
                    "Harap Pilih Data Terlebih Dahulu",
                    "Eror", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String ID = (String) model.getValueAt(i, 0);
        
        try{
            Connection c = koneksi.getkoneksi();
            
            String sql = "DELETE FROM tbdistributor WHERE IDDistributor = ?";
            
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, ID);
            p.executeUpdate();
            p.close();
            
            JOptionPane.showMessageDialog(null,
                    "Hapus Data Berhasil");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,
                    "Terjadi Eror" + e.getMessage());
        }finally{
            loadData();
            kosong();
           
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (! ((Character.isDigit(c) ||
                (c == KeyEvent.VK_BACK_SPACE) ||
                (c == KeyEvent.VK_DELETE))
            )) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Harap Masukan Angka 0-9 Untuk Mengisi ID Distributor!!");
            evt.consume();
      }
    }//GEN-LAST:event_txtidKeyTyped

    private void txtteleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtteleponKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (! ((Character.isDigit(c) ||
                (c == KeyEvent.VK_BACK_SPACE) ||
                (c == KeyEvent.VK_DELETE))
            )) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Nomer Telepon Hanya Bisa Di Isi Menggunakan Angka!!!");
            evt.consume();
      }
    }//GEN-LAST:event_txtteleponKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(distributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(distributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(distributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(distributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new distributor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelbarang;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtkota;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables

}
