/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class EntriDataBarang extends javax.swing.JPanel {

    /**
     * Creates new form EntriDataBarang
     */
    public EntriDataBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKodeBarang = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        cmbKodeJenisBarang = new javax.swing.JComboBox<>();
        txtHargaNet = new javax.swing.JTextField();
        txtHargaJual = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtJenisBarang = new javax.swing.JTextField();
        btnAddNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jLabel10.setText("jLabel10");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Kode Barang");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 28, -1, -1));

        jLabel2.setText("Nama Barang");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 56, -1, -1));

        jLabel3.setText("Kode Jenis Barang");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 81, -1, -1));

        jLabel4.setText("Jenis Barang");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 109, -1, -1));

        jLabel5.setText("Harga Net");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 140, -1, -1));

        jLabel6.setText("Harga Jual");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 168, -1, -1));

        jLabel7.setText("Stok");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 196, -1, -1));
        add(txtKodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 25, -1, -1));
        add(txtNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 53, 299, -1));

        cmbKodeJenisBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih kode barang", "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbKodeJenisBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 81, -1, -1));
        add(txtHargaNet, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 137, 119, -1));
        add(txtHargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 165, 119, -1));
        add(txtStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 193, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 248, 469, 158));
        add(txtJenisBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 109, 300, -1));

        btnAddNew.setText("Add New");
        add(btnAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 424, -1, 22));

        btnSave.setText("Save");
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 424, -1, 22));

        btnUpdate.setText("Update");
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 424, -1, 22));

        btnDelete.setText("Delete");
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 424, -1, 22));

        btnCancel.setText("Cancel");
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 424, -1, 22));

        btnClose.setText("Close");
        add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 424, -1, 22));

        jLabel8.setText("Rp");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 140, -1, -1));

        jLabel9.setText("Rp");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 168, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 480));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbKodeJenisBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtHargaNet;
    private javax.swing.JTextField txtJenisBarang;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
